#include<iostream.h>
#include<conio.h>
#include<stdio.h>
#include<stdlib.h>
class read
{
int a,b,c,d,e,f;
public:
void intros();
void block1();
void block2();
void block3();
void block4();
void block5();
void block6();
void check(int,int,int,int,int,int);
};
void read::intros()
{
cout<<endl<<endl<<endl<<endl<<"\n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++ ";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++ ";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++ ";
cout<<"\n \t \t \t +++ ************************ +++ ";
cout<<"\n \t \t \t +++  ***** MIND READER ****  +++ ";
cout<<"\n \t \t \t +++   ********************   +++ ";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++ ";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++ ";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++ ";
cout<<"\n \n \n \n \n \n \n \n \n \t NOTE: Choose A Number Between (1-60) And Keep It SECRET..!! ";
cout<<"\n \t -----------------------------------------------------------";
cout<<"\n \t Enter Any Key To Continue...: ";
cin.get();
clrscr();
}
void read::block1()
{
cout<<"\n \n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
cout<<"\n \t \t \t +  ** 1  ** 3  ** 5  ** 7  **  +";
cout<<"\n \t \t \t +  ** 9  ** 11 ** 13 ** 15 **  +";
cout<<"\n \t \t \t +  ** 17 ** 19 ** 21 ** 23 **  +";
cout<<"\n \t \t \t +  ** 25 ** 27 ** 29 ** 31 **  +";
cout<<"\n \t \t \t +  ** 33 ** 35 ** 37 ** 39 **  +";
cout<<"\n \t \t \t +  ** 41 ** 43 ** 45 ** 47 **  +";
cout<<"\n \t \t \t +  ** 49 ** 51 ** 53 ** 55 **  +";
cout<<"\n \t \t \t +        ** 57 ** 59 **        + ";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
}
void read::block2()
{
cout<<"\n \n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
cout<<"\n \t \t \t +  ** 2  ** 3  ** 6  ** 7  **  +";
cout<<"\n \t \t \t +  ** 10 ** 11 ** 14 ** 15 **  +";
cout<<"\n \t \t \t +  ** 18 ** 19 ** 22 ** 23 **  +";
cout<<"\n \t \t \t +  ** 26 ** 27 ** 30 ** 31 **  +";
cout<<"\n \t \t \t +  ** 34 ** 35 ** 38 ** 39 **  +";
cout<<"\n \t \t \t +  ** 42 ** 43 ** 46 ** 47 **  +";
cout<<"\n \t \t \t +  ** 50 ** 51 ** 54 ** 55 **  +";
cout<<"\n \t \t \t +        ** 58 ** 59 **        +";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
}
void read::block3()
{
cout<<"\n \n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
cout<<"\n \t \t \t +  ** 4  ** 5  ** 6  ** 7  **  +";
cout<<"\n \t \t \t +  ** 12 ** 13 ** 14 ** 15 **  +";
cout<<"\n \t \t \t +  ** 20 ** 21 ** 22 ** 23 **  +";
cout<<"\n \t \t \t +  ** 28 ** 29 ** 30 ** 31 **  +";
cout<<"\n \t \t \t +  ** 36 ** 37 ** 38 ** 39 **  +";
cout<<"\n \t \t \t +  ** 44 ** 45 ** 46 ** 47 **  +";
cout<<"\n \t \t \t +  ** 52 ** 53 ** 54 ** 55 **  +";
cout<<"\n \t \t \t +           ** 60 **           +";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
}
void read::block4()
{
cout<<"\n \n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
cout<<"\n \t \t \t +  ** 8  ** 9  ** 10 ** 11 **  +";
cout<<"\n \t \t \t +  ** 12 ** 13 ** 14 ** 15 **  +";
cout<<"\n \t \t \t +  ** 24 ** 25 ** 26 ** 27 **  +";
cout<<"\n \t \t \t +  ** 28 ** 29 ** 30 ** 31 **  +";
cout<<"\n \t \t \t +  ** 40 ** 41 ** 42 ** 43 **  +";
cout<<"\n \t \t \t +  ** 44 ** 45 ** 46 ** 47 **  +";
cout<<"\n \t \t \t +  ** 56 ** 57 ** 58 ** 59 **  +";
cout<<"\n \t \t \t +           ** 60 **           +";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
}
void read::block5()
{
cout<<"\n \n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
cout<<"\n \t \t \t +  ** 16 ** 17 ** 18 ** 19 **  +";
cout<<"\n \t \t \t +  ** 20 ** 21 ** 22 ** 23 **  +";
cout<<"\n \t \t \t +  ** 24 ** 25 ** 26 ** 27 **  +";
cout<<"\n \t \t \t +  ** 28 ** 29 ** 30 ** 31 **  +";
cout<<"\n \t \t \t +  ** 48 ** 49 ** 50 ** 51 **  +";
cout<<"\n \t \t \t +  ** 52 ** 53 ** 54 ** 55 **  +";
cout<<"\n \t \t \t +  ** 56 ** 57 ** 58 ** 59 **  +";
cout<<"\n \t \t \t +           ** 60 **           +";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
}
void read::block6()
{
cout<<"\n \n \n";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
cout<<"\n \t \t \t +  ** 32 ** 33 ** 34 ** 35 **  +";
cout<<"\n \t \t \t +  ** 36 ** 37 ** 38 ** 39 **  +";
cout<<"\n \t \t \t +  ** 40 ** 41 ** 42 ** 43 **  +";
cout<<"\n \t \t \t +  ** 44 ** 45 ** 46 ** 47 **  +";
cout<<"\n \t \t \t +  ** 48 ** 49 ** 50 ** 51 **  +";
cout<<"\n \t \t \t +  ** 52 ** 53 ** 54 ** 55 **  +";
cout<<"\n \t \t \t +  ** 56 ** 57 ** 58 ** 59 **  +";
cout<<"\n \t \t \t +           ** 60 **           +";
cout<<"\n \t \t \t ++++++++++++++++++++++++++++++++";
}
void read::check(int a,int b,int c,int d,int e,int f)
{
if(a==0 && b==0 && c==0 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 0";}
if(a==1 && b==0 && c==0 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 1";}
else if(a==0 && b==1 && c==0 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 2";}
else if(a==1 && b==1 && c==0 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 3";}
else if(a==0 && b==0 && c==1 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 4";}
else if(a==1 && b==0 && c==1 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 5";}
else if(a==0 && b==1 && c==1 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 6";}
else if(a==1 && b==1 && c==1 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 7";}
else if(a==0 && b==0 && c==0 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 8";}
else if(a==1 && b==0 && c==0 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 9";}
else if(a==0 && b==1 && c==0 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 10";}
else if(a==1 && b==1 && c==0 && d==0 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 11";}
else if(a==0 && b==0 && c==1 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 12";}
else if(a==1 && b==0 && c==1 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 13";}
else if(a==0 && b==1 && c==1 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 14";}
else if(a==1 && b==1 && c==1 && d==1 && e==0 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 15";}
else if(a==0 && b==0 && c==0 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 16";}
else if(a==1 && b==0 && c==0 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 17";}
else if(a==0 && b==1 && c==0 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 18";}
else if(a==1 && b==1 && c==0 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 19";}
else if(a==0 && b==0 && c==1 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 20";}
else if(a==1 && b==0 && c==1 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 21";}
else if(a==0 && b==1 && c==1 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 22";}
else if(a==1 && b==1 && c==1 && d==0 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 23";}
else if(a==0 && b==0 && c==0 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 24";}
else if(a==1 && b==0 && c==0 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 25";}
else if(a==0 && b==1 && c==0 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 26";}
else if(a==1 && b==1 && c==0 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 27";}
else if(a==0 && b==0 && c==1 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 28";}
else if(a==1 && b==0 && c==1 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 29";}
else if(a==0 && b==1 && c==1 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 30";}
else if(a==1 && b==1 && c==1 && d==1 && e==1 && f==0)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 31";}
else if(a==0 && b==0 && c==0 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 32";}
else if(a==1 && b==0 && c==0 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 33";}
else if(a==0 && b==1 && c==0 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 34";}
else if(a==1 && b==1 && c==0 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 35";}
else if(a==0 && b==0 && c==1 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 36";}
else if(a==1 && b==0 && c==1 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 37";}
else if(a==0 && b==1 && c==1 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 38";}
else if(a==1 && b==1 && c==1 && d==0 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 39";}
else if(a==0 && b==0 && c==0 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 40";}
else if(a==1 && b==0 && c==0 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 41";}
else if(a==0 && b==1 && c==0 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 42";}
else if(a==1 && b==1 && c==0 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 43";}
else if(a==0 && b==0 && c==1 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 44";}
else if(a==1 && b==0 && c==1 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 45";}
else if(a==0 && b==1 && c==1 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 46";}
else if(a==1 && b==1 && c==1 && d==1 && e==0 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 47";}
else if(a==0 && b==0 && c==0 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 48";}
else if(a==1 && b==0 && c==0 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 49";}
else if(a==0 && b==1 && c==0 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 50";}
else if(a==1 && b==1 && c==0 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 51";}
else if(a==0 && b==0 && c==1 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 52";}
else if(a==1 && b==0 && c==1 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 53";}
else if(a==0 && b==1 && c==1 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 54";}
else if(a==1 && b==1 && c==1 && d==0 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 55";}
else if(a==0 && b==0 && c==0 && d==1 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 56";}
else if(a==1 && b==0 && c==0 && d==1 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 57";}
else if(a==0 && b==1 && c==0 && d==1 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 58";}
else if(a==1 && b==1 && c==0 && d==1 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 59";}
else if(a==0 && b==0 && c==1 && d==1 && e==1 && f==1)
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Your Number Is..: 60";}
else
{clrscr();cout<<"\n \n \n \n \n \n \n \n \n \n";
cout<<"\n \t \t \t \t Wrong Choice......!!!";}
}
void main()
{
clrscr();
int a,b,c,d,e,f;
read r;
r.intros();
clrscr();
cout<<"\n \n \t Is Ur Number Present In This Block..?";
cout<<"\n \t---------------------------------------";
r.block1();
cout<<"\n \n \n \n \n \t Enter value (1- if Yes 0r 0- if No)..: ";
cin>>a;
clrscr();
cout<<"\n \n \t Is Ur Number Present In This Block..?";
cout<<"\n \t---------------------------------------";
r.block2();
cout<<"\n \n \n \n \n \t Enter value (1- if Yes 0r 0- if No)..: ";
cin>>b;
clrscr();
cout<<"\n \n \t Is Ur Number Present In This Block..?";
cout<<"\n \t---------------------------------------";
r.block3();
cout<<"\n \n \n \n \n \t Enter value (1- if Yes 0r 0- if No)..: ";
cin>>c;
clrscr();
cout<<"\n \n \t Is Ur Number Present In This Block..?";
cout<<"\n \t---------------------------------------";
r.block4();
cout<<"\n \n \n \n \n \n \t Enter value (1- if Yes 0r 0- if No)..: ";
cin>>d;
clrscr();
cout<<"\n \n \t Is Ur Number Present In This Block..?";
cout<<"\n \t---------------------------------------";
r.block5();
cout<<"\n \n \n \n \n \t Enter value (1- if Yes 0r 0- if No)..: ";
cin>>e;
clrscr();
cout<<"\n \n \t Is Ur Number Present In This Block..?";
cout<<"\n \t---------------------------------------";
r.block6();
cout<<"\n \n \n \n \n \t Enter value (1- if Yes 0r 0- if No)..: ";
cin>>f;
clrscr();
r.check(a,b,c,d,e,f);
cout<<"\n \n \n \n \n \t \t \t Thanks For playing..........!!!";
cout<<"\n \t \t \t     -----------------------";
cout<<"\n \t \t \t      Done By: P.SONU PRIYA";
cout<<"\n \t \t \t     -----------------------";
cout<<"\n \t \t \t With Simple Basic Coding Of C++";
getch();
}
